name: pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repositorio
        uses: actions/checkout@v3

      - name: Lista os arquivos do repo
        run: echo $(ls)

      - name: instala um env com o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: instala o pytest
        run: pip install pytest

      - name: instala o pandas
        run: pip pandas

      - name: Executa o Pytest
        run: pytest